### ISSUE TITLE
About errors in the code

### ISSUE THREAD

**Issue by axin0X** [wuliguozi/CLFuzz#1]
When I tried to make CLFuzz, I found a number of problems with the code, including but not limited to missing semicolons and commas (e.g., line 112 of the 'executor.cpp' file does not include a semicolon), and I found that in line 113 of the 'executor.cpp' file, The code tries to convert an initialization list to type EncryptionKey, but the compiler can't do the conversion, I don't know if it's my environment or if the code itself wasn't fully completed and checked.

**Comment by wuliguozi** [comment]
For some commercial partnership reasons, we were not allowed to open source the full code. Therefore, we open a portion of the code to demonstrate the core idea. The syntax issues were supposedly created during the construction of the open source code, and we apologize for the inconvenience. You can find the corrected version [here](https://github.com/THU-WingTecher/CLFuzz).
